# Generated by Django 4.1.3 on 2022-12-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
