# Generated by Django 4.1.3 on 2022-12-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_last_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
